### ISSUE TITLE
Breaks Sublime Haxe Plugin auto completion

### ISSUE THREAD

**Issue by matulkum** [clemos/haxe-js-kit#87] opened 2015-12-17 22:54 UTC
I wanted to use this Lib for Express. As soon as I use it though Sublime auto completion does not work anymore:

```
package;
class ServerMain {
	public static function main() {
		trace('hello world');
		// here auto completion still works.
		var app = new js.npm.Express();
		// from here on auto completion is broken
 	}	
}
```

I tried all 3 branches ("master", "develop", "haxelib").. I installed via haxelib and via git. No luck. I am on OS X with Haxe 3.2.1

It still compiles ok though. Also there is no error message in Sublime whatsoever. So I am not sure if it is a js-kit issue or a Sublime Plugin issue. Never had that kind of trouble with Sublime before though.

**Comment by clemos** [comment] 2015-12-18 09:23
Please search for similar issues before creating a new one: this is clearly a duplicate of #86

**Closed by clemos** 2015-12-18 09:23 UTC
